# Generated by Django 5.2.12 on 2026-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payuee_transaction_pin',
            field=models.CharField(blank=True, help_text='6-digit PIN for Payuee escrow order authorization', max_length=6, null=True),
        ),
    ]
