# Generated by Django 5.2.12 on 2026-05-16 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0007_remove_product_products_is_feat_19b203_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_payuee__32be8b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='order',
            name='payuee_order_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Selected size (clothing or shoe size from Payuee)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_processed',
            field=models.BooleanField(default=False, help_text='Whether escrow funds have been released/settled'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated delivery days from Payuee', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payuee_order_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Payuee order IDs returned from create_order: [10293, 34523]'),
        ),
        migrations.AddField(
            model_name='order',
            name='payuee_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Validated payload sent to Payuee API'),
        ),
        migrations.AddField(
            model_name='order',
            name='payuee_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response from Payuee API'),
        ),
        migrations.AddField(
            model_name='order',
            name='scanned_qr_code',
            field=models.BooleanField(default=False, help_text='Whether delivery QR code has been scanned'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trans_code',
            field=models.CharField(blank=True, help_text='Customer 6-digit transaction PIN for delivery verification', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='webhook_response_url',
            field=models.URLField(blank=True, help_text='URL where Payuee sends webhook events for this order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payuee_product_id',
            field=models.PositiveIntegerField(blank=True, help_text='Payuee product ID for this item', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payuee_vendor_id',
            field=models.PositiveIntegerField(blank=True, help_text='Payuee vendor ID for this item', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Selected size (outfit_size or shoe_size)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Unique key for Payuee idempotency', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payuee_escrow_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('escrow_locked', 'Escrow Locked'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('released', 'Released'), ('hold', 'On Hold'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Payuee escrow lifecycle status', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'selected_size')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payuee_escrow_status'], name='orders_payuee__95f7be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
    ]
