# Generated by Django 5.2.12 on 2026-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payuee_vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='payuee_product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
