# Generated by Django 5.2.12 on 2026-05-16 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_payuee_vendor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_feat_19b203_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_category',
            field=models.CharField(blank=True, help_text='Payuee category (e.g., outfits, jewelry, gadgets)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_clothing_sizes',
            field=models.CharField(blank=True, help_text='Available clothing sizes from Payuee (e.g., "S,M,L,XL")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_estimated_delivery',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated delivery days from Payuee', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_featured',
            field=models.BooleanField(default=False, help_text='Featured flag from Payuee'),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time product data was synced from Payuee', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product weight in kg from Payuee', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_on_sale',
            field=models.BooleanField(default=False, help_text='On sale flag from Payuee'),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_product_url_id',
            field=models.CharField(blank=True, help_text='Payuee product URL slug (e.g., "italian-shoe-90")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_shoe_sizes',
            field=models.CharField(blank=True, help_text='Available shoe sizes from Payuee (e.g., "30-40")', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_stock_remaining',
            field=models.PositiveIntegerField(blank=True, help_text='Stock count from Payuee API (stock_remaining field)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_tags',
            field=models.JSONField(blank=True, default=list, help_text='Product tags from Payuee API'),
        ),
        migrations.AddField(
            model_name='product',
            name='payuee_vendor_type',
            field=models.CharField(blank=True, help_text='Vendor subscription type (basic, premium, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs. For Payuee products, prepend https://payuee.com/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payuee_product_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Payuee product ID (integer, e.g., 92, 255)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='payuee_vendor_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Payuee vendor ID (eshop_user_id, e.g., 19, 51)', null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['payuee_product_id'], name='products_payuee__5b3775_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['payuee_vendor_id'], name='products_payuee__07ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['payuee_category'], name='products_payuee__315020_idx'),
        ),
    ]
